// GENERATED by scripts/select-plugins.mjs — do not hand-edit.
//
// Regenerate with `npm run select-plugins` (predev/prebuild/pretest already
// do). Which plugins appear here comes from the PLUGINS env var; see
// SPEC.md §4.7a.
//
//   PLUGINS=generic-input,docx-input,xlsx-crate-input,austlang,file-format-identify,ca-data-prep,chat-export,merge,roctable,validate-crate,ro-crate-json-output,ro-crate-xlsx-output,ro-crate-html-output,concordance,ngrams,chart

import { buildDeps } from "./deps.js";
import { createPlugin as create_generic_input } from "collection2crate-plugins/plugins/generic-input/index.js";
import { createPlugin as create_docx_input } from "collection2crate-plugins/plugins/docx-input/index.js";
import { createPlugin as create_xlsx_crate_input } from "collection2crate-plugins/plugins/xlsx-crate-input/index.js";
import { createPlugin as create_austlang } from "collection2crate-plugins/plugins/austlang/index.js";
import { createPlugin as create_file_format_identify } from "collection2crate-plugins/plugins/file-format-identify/index.js";
import { createPlugin as create_ca_data_prep } from "collection2crate-plugins/plugins/ca-data-prep/index.js";
import { createPlugin as create_chat_export } from "collection2crate-plugins/plugins/chat-export/index.js";
import { createPlugin as create_merge } from "collection2crate-plugins/plugins/merge/index.js";
import { createPlugin as create_roctable } from "collection2crate-plugins/plugins/roctable/index.js";
import { createPlugin as create_validate_crate } from "collection2crate-plugins/plugins/validate-crate/index.js";
import { createPlugin as create_ro_crate_json_output } from "collection2crate-plugins/plugins/ro-crate-json-output/index.js";
import { createPlugin as create_ro_crate_xlsx_output } from "collection2crate-plugins/plugins/ro-crate-xlsx-output/index.js";
import { createPlugin as create_ro_crate_html_output } from "collection2crate-plugins/plugins/ro-crate-html-output/index.js";
import { createPlugin as create_concordance } from "collection2crate-plugins/plugins/concordance/index.js";
import { createPlugin as create_ngrams } from "collection2crate-plugins/plugins/ngrams/index.js";
import { createPlugin as create_chart } from "collection2crate-plugins/plugins/chart/index.js";

// One deps object, built once, handed to every factory (SPEC.md §4.7a).
const deps = buildDeps();

/**
 * Every plugin, builders included — array order is hook-execution order for
 * plugins sharing a stage at equal priority. A builder is not a separate kind
 * of plugin: it is one whose crate:build tap sits in the builder band
 * (priority <= BUILDER_PRIORITY) and assembles ctx.crate (SPEC.md §4.5).
 */
export const PLUGINS = [
  create_generic_input(deps),
  create_docx_input(deps),
  create_xlsx_crate_input(deps),
  create_austlang(deps),
  create_file_format_identify(deps),
  create_ca_data_prep(deps),
  create_chat_export(deps),
  create_merge(deps),
  create_roctable(deps),
  create_validate_crate(deps),
  create_ro_crate_json_output(deps),
  create_ro_crate_xlsx_output(deps),
  create_ro_crate_html_output(deps),
  create_concordance(deps),
  create_ngrams(deps),
  create_chart(deps),
];

/** Every plugin's Build-panel option schema, in plugin order. */
export function composeOptionSchema() {
  return PLUGINS.map((plugin) => plugin.optionSchema).filter(Boolean);
}

/** Every plugin's Settings-modal schema, in plugin order. */
export function composeSettingsSchema() {
  return PLUGINS.map((plugin) => plugin.settingsSchema).filter(Boolean);
}

/**
 * Every plugin's Visualise panel, in plugin order.
 *
 * A panel is something a plugin offers, like an option schema — so leaving a
 * plugin out of the PLUGINS selection takes its panel with it (SPEC.md §6.4).
 */
export function composeVisualisationPanels() {
  return PLUGINS
    .filter((plugin) => plugin.visualisation?.render)
    .map((plugin) => ({ name: plugin.name, ...plugin.visualisation }));
}

/**
 * Every path a plugin may write into the picked folder, deduped by path.
 * Used to exclude a previous build's output from the folder scan, and by the
 * "Delete plugin output before rebuilding" setting.
 */
export function composeOutputPaths() {
  const byPath = new Map();
  for (const plugin of PLUGINS) {
    for (const entry of plugin.outputPaths || []) {
      if (entry?.path && !byPath.has(entry.path)) byPath.set(entry.path, entry);
    }
  }
  return [...byPath.values()];
}
